site_name: InterfaceService
use_directory_urls: false
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - admonition
  - footnotes
extra_javascript:
  - 'javascripts/extra.js'